package service_implementation

import (
	"context"
	authentication "project_a/authentication"
	pb "project_a/embedded"

	"google.golang.org/grpc"
)

type Assistant struct {
	//those used for client app info (GCP)
	Client_ID     string
	Client_Secret string
	//Token generated by OAuth2
	Authentication_Info *authentication.Authentication_data
	//embedded interface
	Assistant_Interface
	//Connection stuff
	Canceler   context.CancelFunc
	Contexted  context.Context
	Connection *grpc.ClientConn
}
type Conversation struct {
	//NewConversation to create conversation instance
	a             *Assistant
	Assist_Client pb.EmbeddedAssistant_AssistClient
	Conversation_Interface
}
